language: python
services: mongodb
python:
- '2.7'
- '3.3'
- '3.4'
- pypy
- pypy3
env:
- EVE=0.5.3 MONGOENGINE=0.8.7
- EVE=0.5.3 MONGOENGINE=0.9
- EVE=0.5.3 MONGOENGINE=dev
- EVE=prod MONGOENGINE=0.8.7
- EVE=prod MONGOENGINE=0.9
- EVE=prod MONGOENGINE=dev
- EVE=dev MONGOENGINE=0.8.7
- EVE=dev MONGOENGINE=0.9
- EVE=dev MONGOENGINE=dev
matrix:
  allow_failures:
  - python: pypy3
  fast_finish: true
install:
- sudo apt-get install python-dev python3-dev
- if [[ $EVE == 'dev' ]]; then travis_retry pip install https://github.com/nicolaiarocci/eve/tarball/develop;
  elif [[ $EVE == 'prod' ]]; then travis_retry pip install https://github.com/nicolaiarocci/eve/tarball/master;
  else travis_retry pip install eve==$EVE;
  fi
- if [[ $MONGOENGINE == 'dev' ]]; then travis_retry pip install https://github.com/MongoEngine/mongoengine/tarball/master;
  else travis_retry pip install mongoengine==$MONGOENGINE;
  fi
- travis_retry python setup.py install
script:
- travis_retry python setup.py test
