language: python
python:
  - "3.3"
  - "2.7"
install:
  - pip install flake8
  - pip install -r requirements.txt
script: 
  - flake8 eve_mongoengine
  - python setup.py test
services: 
  - mongodb
before_script:
  - "ulimit -n 1024"
  - mongo eve_test --eval 'db.addUser("test_user", "test_pw");'
branches:
  only:
    - master
